copy "synth\neptUNO\output_files\Segasys1.rbf" "4D Warriors.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Flicky.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Im Sorry.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Mister Viking.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "My Hero.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Rafflesia.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Regulus.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Sega Ninja.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Spatter.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "TeddyBoy Blues.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Up n Down.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Wonder Boy.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Star Jacker.np1"
copy "synth\neptUNO\output_files\Segasys1.rbf" "Pitfall II.np1"