copy "synth\unamiga\output_files\Segasys1.rbf" "4D Warriors.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Flicky.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Im Sorry.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Mister Viking.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "My Hero.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Rafflesia.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Regulus.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Sega Ninja.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Spatter.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "TeddyBoy Blues.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Up n Down.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Wonder Boy.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Star Jacker.rbf"
copy "synth\unamiga\output_files\Segasys1.rbf" "Pitfall II.rbf"